# Site settings
name: João Perdigão
description: "Computer Science Engineer. Living in Zürich. BBQ lover, friendly gamer and sports fan."
#baseurl:"/jppperdigao.github.io/"
url: "http://jppperdigao.github.io/mywebsite"

linkedin_username: joaoperdigao
github_username:  jppperdigao
twitter_username: jppperdigao
facebook_username: jppperdigao
instagram_username:  jppperdigao
email: joao.p.perdigao@gmail.com

avatar: yes
avatar_img_path: "imgs/fotowebpage.jpg"

front_img: yes
front_img_path: "imgs/background.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon3.ico"

markdown: kramdown
permalink: pretty
